var places = ["Makkha","Forest","Turkey","Madina"];
console.log(places);
console.log([...places].sort());
console.log(places);
console.log([...places].sort().reverse());
console.log(places);
console.log(places.reverse());
console.log(places);
console.log(places.reverse());
console.log(places);
console.log(places.sort());
console.log(places.reverse());