var car1;
var car2;
var car3;
var car4;
var car5;
console.log('is car1 Toyota? i predicted ture');
console.log(car1 = 'Toyota');
console.log('is car2 Toyota? i predicted false');
console.log(car2 = 'Honda');
console.log('is car3 Honda? i predicted false');
console.log(car3 = 'Suzuki');
console.log('is car4 Hyundai? i predicted true');
console.log(car4 = 'Hyundai');
console.log('is car5 Audi? i predicted true');
console.log(car5 = 'Audi');
console.log('is car1 Honda? i pridited false');
console.log(car1 = 'Toyota');
console.log('is car2 Honda?i predited true');
console.log(car2 = 'Honda');
console.log('is car3 suzuki? i predicted true');
console.log(car3 = 'Suzuki');
console.log('is car4 Suzuki/ i predicted false');
console.log(car4 = 'Hyundai');
console.log('is car5 Honda?i predited false');
console.log(car5 = 'Audi');
